version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - video_app_network
  redis:
    image: redis
    networks:
      - video_app_network
networks:
  video_app_network:
